### PR TITLE
fixed values call to get values back

### PR DESCRIPTION
**Pull request by bogind**
last version no longer worked, rewrote line 25 to match current appscript syntax

### CODE REVIEW

**Comment by bogind** [comment]
> @googlebot I signed it!

**Comment by sqrrrl** [comment]
That code snippet is for the advanced services version of the Sheets API (basicallly a wrapper around the Sheets REST API), which is a different calling style than the built-in SpreadsheetApp. This change isn't appropriate here.

If there's a problem with the sample, please file an issue. It may just be that you missed a step in enabling the service, which would results in `Sheets` being undefined when executing.

**Comment by sqrrrl** [comment]
This particular sample was meant to show using the sheets APIs through advanced services (basically wrappers around the underlying Rest API) and shouldn't be using SpreadsheetApp.

If there's an issue with the sample or instructions, can you file an issue?

**Comment by contributorpw** [comment]
@sqrrrl more than clear https://developers.google.com/sheets/api/quickstart/apps-script

**Pull request closed without merging**
